name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Trigger on version tags
  pull_request:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up multi-architecture support
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y libseccomp-dev libseccomp-dev:arm64 gcc-aarch64-linux-gnu

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.5'

      - name: Run GoReleaser
        if: startsWith(github.ref, 'refs/tags/') # Only run on tags
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
